default_platform(:android) 

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean" 
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    
    firebase_app_distribution(
      app: "1:238044546348:android:c95e141c6e456351f61889",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "loulouibrahim25@gmail.com",
      release_notes: "First Firebase Fastlane distribution",
  )
  end
end

